name: On Push Workflow

on:
  push:
    branches:
      - "**" # Trigger on all branches
  # workflow_dispatch:  # Manual trigger for debugging

jobs:
  mock-build:
    runs-on: ubuntu-latest

    outputs:
      build_result: ${{ steps.build.outputs.build_result }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Mock Build Result
        id: build
        run: |
          # Simulating a build failure
          echo "build_result=failure" >> $GITHUB_OUTPUT

  trigger-workflows:
    needs: mock-build
    if: needs.mock-build.outputs.build_result == 'failure'
    strategy:
      matrix:
        repository: ["lironm16/ios"]

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow via curl
        env:
          PAT: ${{ secrets.WORKFLOW_TRIGGER_PAT }}
        run: |
          echo "Triggering repository_dispatch event for ${{ matrix.repository }} on branch ${{ github.ref_name }}"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            https://api.github.com/repos/${{ matrix.repository }}/dispatches \
            -d '{"event_type": "rerun-pr-check", "client_payload": {"branch": "${{ github.ref_name }}"}}'
