name: On Push Workflow

on:
  push:
    branches:
      - "**" # Trigger on all branches
  # workflow_dispatch:  # Manual trigger for debugging

jobs:
  mock-build:
    runs-on: ubuntu-latest

    outputs:
      build_result: ${{ steps.build.outputs.build_result }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Mock Build Result
        id: build
        run: |
          # Simulating a build failure
          echo "build_result=failure" >> $GITHUB_OUTPUT

  trigger-workflows:
    needs: mock-build
    if: needs.mock-build.outputs.build_result == 'failure'
    strategy:
      matrix:
        repository: ["lironm16/ios"]

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SHARED_SDK_PAT }}
          repository: ${{ matrix.repository }}
          event-type: rerun-pr-check
          client-payload: '{"ref": "${{ github.ref_name }}"}'
